server.port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/online-shop
    username: postgres
    password: passw0rd
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect